In [2]:
import numpy as np

In [2]:
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [11]:
np.linspace(0,5,8).reshape(2,4)

array([[0.        , 0.71428571, 1.42857143, 2.14285714],
       [2.85714286, 3.57142857, 4.28571429, 5.        ]])

In [8]:
np.random.rand(2)

array([0.14546721, 0.47951571])

In [10]:
np.random.ranf(4)

array([0.22061879, 0.15284136, 0.53622426, 0.35010929])

In [6]:
np.arange(1,12,2)

array([ 1,  3,  5,  7,  9, 11])

In [10]:
arr=np.random.randint(1,100,20)

In [11]:
arr

array([78, 70, 27, 83, 27,  7, 10, 50,  9, 58, 98, 34,  5, 79, 39, 63, 76,
       10, 64, 17])

In [15]:
arr.reshape(5,4)

array([[78, 70, 27, 83],
       [27,  7, 10, 50],
       [ 9, 58, 98, 34],
       [ 5, 79, 39, 63],
       [76, 10, 64, 17]])

In [17]:
arr.max()

98

In [18]:
arr.min()

5

In [22]:
arr.shape

(20,)

In [24]:
arr.reshape(2,10)

array([[78, 70, 27, 83, 27,  7, 10, 50,  9, 58],
       [98, 34,  5, 79, 39, 63, 76, 10, 64, 17]])

In [28]:
arr=np.arange(10)

In [29]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
arr[5:]

array([5, 6, 7, 8, 9])

In [31]:
arr[:5]

array([0, 1, 2, 3, 4])

In [32]:
arr[1:7]

array([1, 2, 3, 4, 5, 6])

In [33]:
arr[0:7]

array([0, 1, 2, 3, 4, 5, 6])

In [35]:
arar=np.arange(10)

In [36]:
arar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
slice_of_arr=arar[0:5]

In [38]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [39]:
slice_of_arr[:]=99

In [40]:
arar

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9])

In [44]:
arr_2d=np.array([[2,3,4],[4,15,65],[98,95,14]])

In [45]:
arr_2d

array([[ 2,  3,  4],
       [ 4, 15, 65],
       [98, 95, 14]])

In [46]:
arr_2d[0][1]

3

In [47]:
arr_2d[2,2]

14

In [55]:
arr_2d[1:,:2]

array([[ 4, 15],
       [98, 95]])

In [65]:
arr=np.random.randint(1,99,10)

In [66]:
arr

array([55,  4, 34, 19, 53, 26,  9, 82, 55, 73])

In [68]:
bool_=arr>30

In [69]:
bool_

array([ True, False,  True, False,  True, False, False,  True,  True,
        True])

In [70]:
arr[bool_]

array([55, 34, 53, 82, 55, 73])

In [71]:
ara=np.arange(32).reshape(4,8)

In [73]:
ara

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [75]:
ara[1:3,2:4]

array([[10, 11],
       [18, 19]])

In [3]:
arr=np.arange(0,10)

In [4]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
1/arr

/home/prudhvi/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [7]:
np.count_nonzero(arr)

9